name: Art Blog
favicon: null
layout_spectrum: 0.705193544505164
typography_spectrum: 0.6712636901065707
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76727504-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#898989'
    - '#4a4a4a'
    - '#ffffff'
    - '#c0c0c0'
  brandStrength: 0.820502833230421
  lightness: 0.7204429996199906
  saturation: 0.550985666224733
  rhythmicContrast: 0.36064521851949394
purpose: []
